"""
Mock candidate database.
In production this would be replaced by an ATS integration or database query.
"""
from models.schemas import Candidate, CandidateStatus
from typing import List

CANDIDATE_DATABASE: List[Candidate] = [
    Candidate(
        candidate_id="cand-001",
        name="Arjun Sharma",
        email="arjun.sharma@email.com",
        phone="+91-9876543210",
        current_role="Senior Software Engineer",
        years_of_experience=6,
        skills=["Python", "FastAPI", "PostgreSQL", "Docker", "Kubernetes", "AWS", "Redis", "LangChain"],
        education="B.Tech Computer Science - IIT Bombay",
        location="Bangalore, India",
        linkedin_url="https://linkedin.com/in/arjunsharma",
        resume_summary="6 years of backend engineering with strong Python/FastAPI expertise. Built microservices at scale.",
        source="LinkedIn",
        status=CandidateStatus.SOURCED,
    ),
    Candidate(
        candidate_id="cand-002",
        name="Priya Nair",
        email="priya.nair@email.com",
        phone="+91-9123456789",
        current_role="ML Engineer",
        years_of_experience=4,
        skills=["Python", "TensorFlow", "PyTorch", "LangChain", "HuggingFace", "FastAPI", "AWS"],
        education="M.Tech Artificial Intelligence - IIT Madras",
        location="Chennai, India",
        linkedin_url="https://linkedin.com/in/priyanair",
        resume_summary="4 years in ML engineering. Specialized in NLP and LLM fine-tuning. Open-source contributor.",
        source="Naukri",
        status=CandidateStatus.SOURCED,
    ),
    Candidate(
        candidate_id="cand-003",
        name="Rohit Verma",
        email="rohit.verma@email.com",
        phone="+91-9988776655",
        current_role="Full Stack Developer",
        years_of_experience=3,
        skills=["React", "Node.js", "Python", "MongoDB", "Docker", "TypeScript"],
        education="B.E. Information Technology - VIT Vellore",
        location="Pune, India",
        linkedin_url="https://linkedin.com/in/rohitverma",
        resume_summary="3 years full-stack experience. Strong React frontend and Node.js backend skills.",
        source="GitHub",
        status=CandidateStatus.SOURCED,
    ),
    Candidate(
        candidate_id="cand-004",
        name="Sneha Kulkarni",
        email="sneha.kulkarni@email.com",
        phone="+91-8765432109",
        current_role="DevOps Engineer",
        years_of_experience=5,
        skills=["Kubernetes", "Docker", "AWS", "Terraform", "CI/CD", "Python", "Ansible", "Jenkins"],
        education="B.E. Computer Engineering - COEP Pune",
        location="Mumbai, India",
        linkedin_url="https://linkedin.com/in/snehakulkarni",
        resume_summary="5 years DevOps with cloud-native expertise. Led migration of 50+ services to Kubernetes.",
        source="LinkedIn",
        status=CandidateStatus.SOURCED,
    ),
    Candidate(
        candidate_id="cand-005",
        name="Karthik Rajan",
        email="karthik.rajan@email.com",
        phone="+91-9000112233",
        current_role="Data Scientist",
        years_of_experience=7,
        skills=["Python", "Spark", "Hadoop", "Machine Learning", "SQL", "Tableau", "Scikit-learn", "Kafka"],
        education="M.Sc Data Science - ISI Kolkata",
        location="Hyderabad, India",
        linkedin_url="https://linkedin.com/in/karthikrajan",
        resume_summary="7 years in data science and engineering. Specializes in large-scale data pipelines and ML deployment.",
        source="Referral",
        status=CandidateStatus.SOURCED,
    ),
    Candidate(
        candidate_id="cand-006",
        name="Ananya Iyer",
        email="ananya.iyer@email.com",
        phone="+91-8900123456",
        current_role="Backend Engineer",
        years_of_experience=2,
        skills=["Java", "Spring Boot", "MySQL", "REST APIs", "Docker"],
        education="B.Tech CSE - NIT Trichy",
        location="Bangalore, India",
        linkedin_url="https://linkedin.com/in/ananyaiyer",
        resume_summary="2 years backend engineering with Java and Spring Boot. Good fundamentals, fast learner.",
        source="Campus",
        status=CandidateStatus.SOURCED,
    ),
    Candidate(
        candidate_id="cand-007",
        name="Vikram Mehta",
        email="vikram.mehta@email.com",
        phone="+91-9700345678",
        current_role="AI/ML Engineer",
        years_of_experience=5,
        skills=["Python", "LangChain", "OpenAI API", "RAG", "FastAPI", "Vector Databases", "Pinecone", "AWS"],
        education="B.Tech AI & Data Science - IIIT Hyderabad",
        location="Remote",
        linkedin_url="https://linkedin.com/in/vikrammehta",
        resume_summary="5 years building AI-powered applications. Expert in LLMs, RAG pipelines, and AI agents.",
        source="LinkedIn",
        status=CandidateStatus.SOURCED,
    ),
    Candidate(
        candidate_id="cand-008",
        name="Divya Reddy",
        email="divya.reddy@email.com",
        phone="+91-9600234567",
        current_role="Product Manager",
        years_of_experience=6,
        skills=["Product Strategy", "Agile", "Jira", "SQL", "User Research", "A/B Testing", "Roadmapping"],
        education="MBA - IIM Ahmedabad",
        location="Delhi, India",
        linkedin_url="https://linkedin.com/in/divyareddy",
        resume_summary="6 years PM experience across B2B SaaS and consumer products. Strong data-driven decision making.",
        source="LinkedIn",
        status=CandidateStatus.SOURCED,
    ),
]


def get_all_candidates() -> List[Candidate]:
    return CANDIDATE_DATABASE
